/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { PluginManagerSetEnabledRequest, PluginManagerSetEnabledResult } from 'dsh-plugin-sidebar-manager/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706c7567696e4d616e61676572 {
    setEnabled: (request: PluginManagerSetEnabledRequest) => Promise<RemoteResult<PluginManagerSetEnabledResult>>
  }
  interface TypertRemoteMap {
    'pluginManager/setEnabled': (request: PluginManagerSetEnabledRequest) => Promise<RemoteResult<PluginManagerSetEnabledResult>>
  }
  interface TypertRemoteNamespaceMap {
    'pluginManager': TypertRemoteNamespace$706c7567696e4d616e61676572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
