/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_plugin_sidebar_manager_pluginManager_setEnabled_parameter_0$schema = z.object({
  'entryId': z.intersection(z.string(), z.unknown()).readonly(),
  'enabled': z.boolean().readonly(),
})
const dsh_plugin_sidebar_manager_pluginManager_setEnabled_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'message': z.string().readonly().optional(),
})

export const TYPERT = {
  package: 'dsh-plugin-sidebar-manager',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-plugin-sidebar-manager#pluginManager/setEnabled',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'setEnabled',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plugin-sidebar-manager/types#PluginManagerSetEnabledRequest',
            schema: dsh_plugin_sidebar_manager_pluginManager_setEnabled_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plugin-sidebar-manager/types#PluginManagerSetEnabledResult',
        schema: dsh_plugin_sidebar_manager_pluginManager_setEnabled_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/plugin-manager/src/index.ts","line":31,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
